### ISSUE TITLE
How to handle RefreshIndicator with it ?

### ISSUE THREAD

**Issue by J920** [dmt195/tiktok-flutter-plugin#10] opened 2021-12-21 12:06 UTC

**Comment by fakerybakery** [comment] 2023-08-08 01:03
Has anyone found a solution to this issue?

**Comment by fakerybakery** [comment] 2023-08-08 20:04
I was able to find a partial solution to this issue. My solution doesn't use RefreshIndicator, but achieves the same functionality. [This line](https://github.com/dmt195/tiktok-flutter-plugin/blob/ce8efecf758fc44665d6a7269e538899b50574ba/lib/tiktoklikescroller.dart#L150) calls the callback with the direction `BACKWARDS` and the success status `FAILED_END_OF_LIST`.

This snippet should do the trick:

```dart
// Important part:
final  Controller _tkController =  Controller();
_tkController.addListener((event) { // This is the important part
	if ((event.direction ==  ScrollDirection.BACKWARDS) && (event.success ==  ScrollSuccess.FAILED_END_OF_LIST)) { // <- listen for the `FAILED_END_OF_LIST` status and check if the scroll direction is `BACKWARDS` (indicating 
		print("Refreshing");
	}
});
return TikTokStyleFullPageScroller(
	contentSize: 10,
	controller: _tkController, // <- this adds the controller
	builder: (context, index) {
		return Text("Item #${index}");
	},
}
```

The problem is that it doesn't always trigger the refresh. The user must overscroll all the way to trigger the refresh action.

**Comment by dmt195** [comment] 2023-08-09 17:14
It is possible to set the threshold triggers lower when initialising `TikTokStyleFullPageScroller` (with `swipePositionThreshold`). I can see how that might not always be appropriate for this.

Would it be useful if the `FAILED_END_OF_LIST` event also returned an optional amount scrolled (either in px or fractions of the card height)?
Then you could add some additional checks to test if you need to do a refresh:
```
final  Controller _tkController =  Controller();
_tkController.addListener((event) { // This is the important part
	if ((event.direction ==  ScrollDirection.BACKWARDS) && (event.success ==  ScrollSuccess.FAILED_END_OF_LIST) && (event.scrollPostionMet > 0.1)) { // <- listen for the `FAILED_END_OF_LIST` status and check if the scroll direction is `BACKWARDS` and the threshold is in the desired range
		print("Refreshing");
	}
});
```

**Comment by fakerybakery** [comment] 2023-08-11 01:39
Yes, this could be useful. Thank you!

**Comment by fakerybakery** [comment] 2023-08-11 01:40
Update: I found that `PageView.builder` achieves the same effect (but with fewer features such as listeners) and has a smoother animation.

Example:
```dart
PageView.builder(
  itemCount: items.length,
  scrollDirection: Axis.vertical,
  itemBuilder: ...
)
```

**Comment by dmt195** [comment] 2023-11-18 22:52
I have now added the extra callback param so will close this issue. See build v0.2.6.

**Closed by dmt195** 2023-11-18 22:52 UTC
